using FactoryGenerator.Abstractions;
using InjectDemo;
using Microsoft.Extensions.DependencyInjection;
using System;
using AutoGeneratedNamespaceFromFactoryGenerator;

Console.WriteLine("Hello, World!");
var services = new ServiceCollection();
services.RegisterGeneratedFactories();
var prov = services.BuildServiceProvider();
var factory = prov.GetRequiredService<IFactory<PersonType, PersonFactory>>();
var factoryEmployee = factory.Create(PersonType.Employee);
Console.WriteLine(factoryEmployee.Create().TypeName);