namespace GeneratorData;

public enum Category
{
    None = 0,
    EnhancementProject,
    Constructor,
    MVVM,
    Builder,
    EnhancementClass,
    Mapper,
    DependencyInjection,
    FilesToCode,
    CodeToString,
    FunctionalProgramming,
    PrimitiveObsession,
    Templating,
    Tests,
    Database,
    API,
    Serializer,
    Optimizer,
    Disposer,
    Enum,
    Interface,
    Blazor,
    Hangfire,
    AOP,
    Bitwise,
    Actor,
    Mediator=26,
    SignalR=27,
    WinAPI = 28,
    Clone=29,
    Equals= 30, 
    Linq=31,
    CommandLine=32,
    StateMachine=33, 
    Console=34,
    Async=35,
    MVC=36,
    AI=37,
    RX=38,
}

