//This file was generated by Tortuga Shipwright

namespace MixinConsoleDemo
{
	partial class Employee
	{

		// These fields and/or properties hold the traits. They should not be referenced directly.
		private MixinConsoleDemo.Person __Trait0 = new();

		// Exposing trait MixinConsoleDemo.Person

		
		public   System.Int32 Age
		{
			get => __Trait0.Age;
			set => __Trait0.Age = value;
		}
		
		public   System.String Name
		{
			get => __Trait0.Name;
			set => __Trait0.Name = value;
		}
	}
}
