name: BuildAndDeploy

on:
  push:
    branches: [ "main" ]

jobs:

  call-workflow-passing-data:
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/compile.yml
    with:
      nodeVersion: 18.13.0

  build:
    needs:
      - call-workflow-passing-data      
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 18.13.0
        # cache: 'npm'
    - run: |
        cd v2 
        cd rscg_examples_site
        npm i
        npm run build 
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: docsv2
        path: 'v2/rscg_examples_site/build/*'
        retention-days: 1

    - name: upload documentation to github pages
      run: |
        cp -r v2/rscg_examples_site/build/* docs/v2/

    - uses: EndBug/add-and-commit@v9
      with:
        message: 'Deploy documentation'
        default_author: github_actions
        cwd: './docs'

