name: BuildAndDeploy

on:
  push:
    tags:
      - 'v*'

jobs:

  call-workflow-passing-data:
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/compile.yml
    with:
      nodeVersion: 20.9.0

  build:
    needs:
      - call-workflow-passing-data      
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 20.9.0
        cache: 'npm'
        cache-dependency-path: "./v2/rscg_examples_site/package-lock.json"

    - run: |
        cd v2 
        cd rscg_examples_site
        npm i
        npm run build 
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        name: docsv2
        path: 'v2/rscg_examples_site/build/*'
        retention-days: 1

    - name: upload documentation to github pages
      run: |
        cp -r v2/rscg_examples_site/build/* docs/v2/
        git config --global user.email "ignatandrei@yahoo.com"
        git config --global user.name "Andrei Ignat Automation"
        git add docs/v2
        git commit -m "Deploy documentation"
        git push origin HEAD:main  
    # - uses: EndBug/add-and-commit@v9
    #   with:
    #     message: 'Deploy documentation'
    #     pull: '-v'
    #     default_author: github_actions
    #     cwd: './docs'

